coverage_service: coveralls
workspace: GSKStretchyHeaderView.xcworkspace
xcodeproj: Example/Example.xcodeproj
scheme: Example
source_directory: Pod/Classes
build_directory: build/GSKStretchyHeaderView/
ignore:
  - Example/*
  - ../**