coverage_service: coveralls
workspace: GSKStretchyHeaderView.xcworkspace
scheme: Example
source_directory: Pod/Classes
build_directory: build
ignore:
  - Example/*
  - Example/GSKStretchyHeaderView/*
