coverage_service: coveralls
workspace: GSKStretchyHeaderView.xcworkspace
xcodeproj: GSKStretchyHeaderView/GSKStretchyHeaderView.xcodeproj
scheme: GSKStretchyHeaderView
source_directory: GSKStretchyHeaderView/Classes
build_directory: build/
ignore:
  - Example/*
  - ../**